In [4]:
# Julia part
#install packages
using Pkg

In [9]:
Pkg.add("HTTP")
Pkg.add("Gumbo")
Pkg.add("Cascadia")
pkg.add("DataFrames")

   Resolving package versions...

LoadError: Unsatisfiable requirements detected for package HTTP [cd3eb016]:
 HTTP [cd3eb016] log:
 ├─possible versions are: 0.6.10-0.9.16 or uninstalled
 └─restricted to versions 0.9.15 by an explicit requirement — no versions left

In [10]:
using HTTP, Gumbo, Cascadia, DataFrames

In [11]:
# Scraping turners.co.nz cars data in julia 
# getting web page
Url = "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/?sortorder=7&pagesize=24&pageno=1"
cars_page = HTTP.get(Url)

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Set-Cookie: ASP.NET_SessionId=bn23sjsnbi0zxhneiuvy1obd; path=/; HttpOnly; SameSite=Lax
Set-Cookie: ASP.NET_SessionId=bn23sjsnbi0zxhneiuvy1obd; path=/; HttpOnly; SameSite=Lax
Set-Cookie: X-TRACK-ID=234bd287-3267-467e-a799-3af7683dca07; expires=Sat, 11-Oct-2031 11:00:00 GMT; path=/
Set-Cookie: HomePageMessage=False; expires=Fri, 31-Dec-2021 09:00:00 GMT; path=/
Date: Mon, 11 Oct 2021 21:41:28 GMT
Content-Length: 255885
Set-Cookie: TS0181a608=015f9f83190639fe144f25cde5251ff608e40f5afbe8e7cc081d3196285fc31d76333bbcecf4014951b911f7fe96d88d2100c8865996a8721eebef952f390ba92a3396c1e940c54861d3cd7b7cbd064c2e69e8e91ae9d9c6d3d06e87dcbe6eb53df6746d624438a05626338678a29ed626ed27f165; Path=/


<!DOCTYPE html>
<html lang="en-NZ">

<head>


<title>Nearly 3,000 used cars across NZ at Turners Cars.  Over 1,000 used cars on sale at any time. | Turners</title>

<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, shrink-to-fit=no">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />


    <meta name="keywords" content="used cars nz, used cars, used car, used cars for sale, used cars for sale nz" />
    <meta name="description" content="Find a used car from a huge range of nearly 3,000 cars for sale. New Zealand&#39;s largest used car network." />

<link href="/Cars/Used-Cars-for-Sale/" rel="canonical" />


<meta property="og:url" content="/Cars/Used-Cars-for-Sale/">
<meta property="og:image" content="https://content.tgstatic.co.nz
⋮
255885-byte body
"""

In [12]:
# parse the html 
parsed_page = cars_page.body |> String |> parsehtml

HTML Document:
<!DOCTYPE html>
HTMLElement{:HTML}:<HTML lang="en-NZ">
  <head>
    <title>
      Nearly 3,000 used cars across NZ at Turners Cars.  Over 1,000 used cars on sale at any time. | Turners
    </title>
    <meta charset="utf-8"/>
    <meta content="ie=edge" http-equiv="x-ua-compatible"/>
    <meta content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="yes" name="apple-mobile-web-app-capable"/>
    <meta content="black" name="apple-mobile-web-app-status-bar-style"/>
    <meta content="used cars nz, used cars, used car, used cars for sale, used cars for sale nz" name="keywords"/>
    <meta content="Find a used car from a huge range of nearly 3,000 cars for sale. New Zealand&#39;s largest used car network." name="description"/>
    <link href="/Cars/Used-Cars-for-Sale/" rel="canonical"/>
    <meta content="/Cars/Used-Cars-for-Sale/" property="og:url"/>
    <meta content="https://content.tgstatic.co.nz/webassets/assets/images/logo/square_logo_car.png" property="og:image"/>
    <meta content="Nearly 3,000 used cars across NZ at Turners Cars.  Over 1,000 used cars on sale at any time. | Turners" property="og:title"/>
    <meta content="Find a used car from a huge range of nearly 3,000 cars for sale. New Zealand&#39;s largest used car network." property="og:description"/>
    <link href="https://content.tgstatic.co.nz/webassets/assets/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <link as="font" crossorigin="" href="https://content.tgstatic.co.nz/webassets/assets/fonts/lato/lato-v16-latin-ext_latin-regular.woff2" rel="preload" type="font/woff2"/>
    <link as="font" crossorigin="" href="https://content.tgstatic.co.nz/webassets/assets/fonts/lato/lato-v16-latin-ext_latin-italic.woff2" rel="preload" type="font/woff2"/>
...

In [47]:
#getting the car names, location, price data using css selector
car_name = Selector(".search-header")
Carname_title = eachmatch(car_name, parsed_page.root)
location = Selector(".location .value")
Location = eachmatch(location,parsed_page.root)
price = Selector(".buyNowDiscountPrice")
Price = eachmatch(price, parsed_page.root)
finance= Selector(".finance span")
Finance= eachmatch(finance, parsed_page.root)
odometer= Selector(".odometer span")
Odometer = eachmatch(odometer, parsed_page.root)

24-element Vector{HTMLNode}:
 HTMLElement{:span}:<span itemprop="value">
  59,043
</span>


 HTMLElement{:span}:<span itemprop="value">
  89,116
</span>


 HTMLElement{:span}:<span itemprop="value">
  55,214
</span>


 HTMLElement{:span}:<span itemprop="value">
  37,067
</span>


 HTMLElement{:span}:<span itemprop="value">
  154,783
</span>


 HTMLElement{:span}:<span itemprop="value">
  181,340
</span>


 HTMLElement{:span}:<span itemprop="value">
  79,044
</span>


 HTMLElement{:span}:<span itemprop="value">
  90,498
</span>


 HTMLElement{:span}:<span itemprop="value">
  114,460
</span>


 HTMLElement{:span}:<span itemprop="value">
  142,271
</span>


 HTMLElement{:span}:<span itemprop="value">
  93,386
</span>


 HTMLElement{:span}:<span itemprop="value">
  33,207
</span>


 HTMLElement{:span}:<span itemprop="value">
  80,240
</span>


 HTMLElement{:span}:<span itemprop="value">
  88,141
</span>


 HTMLElement{:span}:<span itemprop="value">
  179,569
</span>


 HTMLElement{:span}:<span itemprop="value">
  75,947
</span>


 HTMLElement{:span}:<span itemprop="value">
  43,029
</span>


 HTMLElement{:span}:<span itemprop="value">
  91,702
</span>


 HTMLElement{:span}:<span itemprop="value">
  56,676
</span>


 HTMLElement{:span}:<span itemprop="value">
  116,186
</span>


 HTMLElement{:span}:<span itemprop="value">
  89,219
</span>


 HTMLElement{:span}:<span itemprop="value">
  74,300
</span>


 HTMLElement{:span}:<span itemprop="value">
  104,572
</span>


 HTMLElement{:span}:<span itemprop="value">
  48,042
</span>

In [30]:
# getting text 
result_string = nodeText.(Carname_title) 
join(result_string, " ") |> println 
result_string1 = nodeText.(Location) 
join(result_string1, " ") |> println 
result_string2 = nodeText.(Price) 
join(result_string2, " ") |> println 
result_string3 = nodeText.(Finance) 
join(result_string3, " ") |> println 
result_string4 = nodeText.(Odometer) 
join(result_string4, " ") |> println

2013 Toyota Prius 2013 Toyota Prius L 2010 Volkswagen Polo 2008 Toyota Crown 2015 Subaru Levorg 4WD 2016 Holden Commodore VF2 Evoke 2011 Volvo S60 2006 Mitsubishi Outlander 4WD 2008 Subaru Forester 2013 Nissan Fuga 2009 Nissan X-Trail 4WD 2018 Toyota Yaris GX 2008 Honda CRV 4WD 2014 Toyota Prius 2009 Nissan X-Trail ST-L 4WD 2007 Lexus GS350 2008 Toyota Blade 2012 Honda Accord Tourer 2008 Toyota Vanguard 4WD 2009 Volkswagen Golf TSI 118KW 2014 Honda Vezel 1500 2WD 2010 Subaru Forester 4WD 2015 Mazda Atenza 2007 Nissan Fuga
Christchurch City Christchurch City Otahuhu Penrose - Great South Road Panmure Avalon Drive Penrose - Great South Road Manukau Panmure Palmerston North Christchurch City Westgate Penrose - Great South Road Christchurch City Avalon Drive Penrose - Great South Road Panmure Botany Panmure Penrose - Great South Road Palmerston North Panmure Christchurch City Christchurch City
$13,900Plus ORC $12,140Plus ORC $9,450Plus ORC $11,890Plus ORC $15,480 $14,890 $14,800 $12,440Plus ORC $10,950Plus ORC $13,990Plus ORC $12,800Plus ORC $16,290 $14,800Plus ORC $13,800Plus ORC $10,450 $9,740Plus ORC $11,450Plus ORC $15,450Plus ORC $15,450Plus ORC $10,740 $18,490Plus ORC $13,980Plus ORC $17,800Plus ORC $11,140Plus ORC
$81 per week $72 per week $57 per week $70 per week $87 per week $84 per week $83 per week $73 per week $65 per week $81 per week $75 per week $91 per week $86 per week $80 per week $60 per week $59 per week $68 per week $89 per week $89 per week $62 per week $105 per week $81 per week $102 per week $66 per week

                            59,043

                            89,116

                            55,214

                            37,067

                            154,783

                            181,340

                            79,044

                            90,498

                            114,460

                            142,271

                            93,386

                            33,207

                            80,240

                            88,141

                            179,569

                            75,947

                            43,029

                            91,702

                            56,676

                            116,186

                            89,219

                            74,300

                            104,572

                            48,042

In [32]:
# using function  to make dataframe
function get_cars_info(link)
  response = HTTP.request("GET","https://www.turners.co.nz/Cars/Used-Cars-for-Sale/?sortorder=7&pagesize=24&pageno=1") 
  parsed_page = response.body |> String |> parsehtml
  parsed_page_part = eachmatch(Carname_title, Location, Price, Finance, Odometer, parsed_page.root)
  array_string = nodeText.(result_string, result_string1, result_string2, result_string3, result_string4, parsed_page_part) 
  result_str = join(array_string, " ")
  df = DataFrame(Link = link, Info = result_str)
  return df
end

get_cars_info (generic function with 1 method)

In [45]:
df

24×5 DataFrame
 Row │ CAR_NAME                         LOCATION                    PRICE      ⋯
     │ String                           String                      String     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2013 Toyota Prius                Christchurch City           $13,900Plu ⋯
   2 │ 2013 Toyota Prius L              Christchurch City           $12,140Plu
   3 │ 2010 Volkswagen Polo             Otahuhu                     $9,450Plus
   4 │ 2008 Toyota Crown                Penrose - Great South Road  $11,890Plu
   5 │ 2015 Subaru Levorg 4WD           Panmure                     $15,480    ⋯
   6 │ 2016 Holden Commodore VF2 Evoke  Avalon Drive                $14,890
   7 │ 2011 Volvo S60                   Penrose - Great South Road  $14,800
   8 │ 2006 Mitsubishi Outlander 4WD    Manukau                     $12,440Plu
   9 │ 2008 Subaru Forester             Panmure                     $10,950Plu ⋯
  10 │ 2013 Nissan Fuga                 Palmerston North            $13,990Plu
  11 │ 2009 Nissan X-Trail 4WD          Christchurch City           $12,800Plu
  ⋮  │                ⋮                             ⋮                      ⋮   ⋱
  15 │ 2009 Nissan X-Trail ST-L 4WD     Avalon Drive                $10,450
  16 │ 2007 Lexus GS350                 Penrose - Great South Road  $9,740Plus ⋯
  17 │ 2008 Toyota Blade                Panmure                     $11,450Plu
  18 │ 2012 Honda Accord Tourer         Botany                      $15,450Plu
  19 │ 2008 Toyota Vanguard 4WD         Panmure                     $15,450Plu
  20 │ 2009 Volkswagen Golf TSI 118KW   Penrose - Great South Road  $10,740    ⋯
  21 │ 2014 Honda Vezel 1500 2WD        Palmerston North            $18,490Plu
  22 │ 2010 Subaru Forester 4WD         Panmure                     $13,980Plu
  23 │ 2015 Mazda Atenza                Christchurch City           $17,800Plu
  24 │ 2007 Nissan Fuga                 Christchurch City           $11,140Plu ⋯
                                                    3 columns and 3 rows omitted

In [44]:
#  one more way to make dataframe
CARS_DF = DataFrame(CAR_NAME = result_string , LOCATION =  result_string1, PRICE = result_string2, FINANCE = result_string3, ODOMETER = result_string4)
CARS_DF

24×5 DataFrame
 Row │ CAR_NAME                         LOCATION                    PRICE      ⋯
     │ String                           String                      String     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2013 Toyota Prius                Christchurch City           $13,900Plu ⋯
   2 │ 2013 Toyota Prius L              Christchurch City           $12,140Plu
   3 │ 2010 Volkswagen Polo             Otahuhu                     $9,450Plus
   4 │ 2008 Toyota Crown                Penrose - Great South Road  $11,890Plu
   5 │ 2015 Subaru Levorg 4WD           Panmure                     $15,480    ⋯
   6 │ 2016 Holden Commodore VF2 Evoke  Avalon Drive                $14,890
   7 │ 2011 Volvo S60                   Penrose - Great South Road  $14,800
   8 │ 2006 Mitsubishi Outlander 4WD    Manukau                     $12,440Plu
   9 │ 2008 Subaru Forester             Panmure                     $10,950Plu ⋯
  10 │ 2013 Nissan Fuga                 Palmerston North            $13,990Plu
  11 │ 2009 Nissan X-Trail 4WD          Christchurch City           $12,800Plu
  ⋮  │                ⋮                             ⋮                      ⋮   ⋱
  15 │ 2009 Nissan X-Trail ST-L 4WD     Avalon Drive                $10,450
  16 │ 2007 Lexus GS350                 Penrose - Great South Road  $9,740Plus ⋯
  17 │ 2008 Toyota Blade                Panmure                     $11,450Plu
  18 │ 2012 Honda Accord Tourer         Botany                      $15,450Plu
  19 │ 2008 Toyota Vanguard 4WD         Panmure                     $15,450Plu
  20 │ 2009 Volkswagen Golf TSI 118KW   Penrose - Great South Road  $10,740    ⋯
  21 │ 2014 Honda Vezel 1500 2WD        Palmerston North            $18,490Plu
  22 │ 2010 Subaru Forester 4WD         Panmure                     $13,980Plu
  23 │ 2015 Mazda Atenza                Christchurch City           $17,800Plu
  24 │ 2007 Nissan Fuga                 Christchurch City           $11,140Plu ⋯
                                                    3 columns and 3 rows omitted